version: "3.9"
services:
  postgres-db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credit_system
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    build: .
    container_name: backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=credit_system
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/credit_system"
    command: /bin/bash docker-entrypoint.sh
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:

